name: Build website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sass install
        run: sudo npm install -g sass
      - name: Make css files
        run: ./scripts/make.sh
      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: .
          retention-days: 5
